### ISSUE TITLE
Traitlets 5.0.0 breaks command line arguments passed to ipykernel launch

### ISSUE THREAD

**Issue by IanMatthewHuff** [ipython/ipykernel#543]
Hey folks. I'm a developer on the VSCode python extension. We install newest ipykernel for customers on request to use our extension and just last night all new environments created in this way were broken.

https://github.com/microsoft/vscode-python/issues/13701

Playing around with the installed packages I traced it to the new traitlets 5.0.0 dependency. And I found this issue there:
https://github.com/ipython/traitlets/issues/608

Which I believe is what is happening to us as well (we pass in the message key signature on the command line to ipykernel and that command line flag is getting ignored). I upvoted that issue in traitlets, but wanted to file here as well as I wasn't sure if ownership of the issue better here or there.

**Comment by blink1073** [comment]
Hi @IanMatthewHuff, can you please point to me to the relevant code in `vscode` or give an example of how you are calling `ipykernel`?

**Comment by IanMatthewHuff** [comment]
@blink1073 Of course. Here is the basic starting point for our kernel launch code:
https://github.com/microsoft/vscode-python/blob/2b007d1331e45d4c7e4a9813b666bbf60566bb53/src/client/datascience/kernel-launcher/kernelProcess.ts#L63

We build out some connection args here, trying to recall back as to the reason, but I believe that we had to use the command parameters here as opposed to just the connection file. Possibly for the --Session parameters. 
https://github.com/microsoft/vscode-python/blob/2b007d1331e45d4c7e4a9813b666bbf60566bb53/src/client/datascience/kernel-launcher/kernelProcess.ts#L193

Probably the more relevant part here is the actual command line run. This is what an example looks like from our logging:
`Info 2020-09-01 15:31:42: Python Daemon (pid: 16117): Exec in DS Kernel Launcher Daemon (observable) ['/Users/kv/.pyenv/versions/bug/bin/python', '-m', 'ipykernel_launcher', '--ip=127.0.0.1', '--stdin=9013', '--control=9011', '--hb=9010', '--Session.signature_scheme="hmac-sha256"', '--Session.key=b"53cba141-3c99-42db-8037-0b593430d63c"', '--shell=9012', '--transport="tcp"', '--iopub=9014', '--f=/var/folders/cn/ht7pqf_j1hg6l7b552dnfvrw0000gn/T/tmp-15704wU9fov65LOG4.json']`

Anything that I can help with on my end? My python expertise is low, so I have not currently dug in much aside from seeing that the traitlet rollback fixed our issue. But I'd love to help if I can.

**Comment by blink1073** [comment]
I think the issue is the binary specifier in `Session.key`:

```python
>>> from ipykernel import kernelapp as app
>>> app.launch_new_instance(['--Session.signature_scheme', "hmac-sha256", "--Session.key", b"53cba141-3c99-42db-8037-0b593430d63c"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/traitlets/config/application.py", line 837, in launch_instance
    app.initialize(argv)
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/traitlets/config/application.py", line 86, in inner
    return method(app, *args, **kwargs)
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 559, in initialize
    super(IPKernelApp, self).initialize(argv)
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/traitlets/config/application.py", line 86, in inner
    return method(app, *args, **kwargs)
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/IPython/core/application.py", line 450, in initialize
    self.parse_command_line(argv)
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/traitlets/config/application.py", line 86, in inner
    return method(app, *args, **kwargs)
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/traitlets/config/application.py", line 666, in parse_command_line
    self.argv = [cast_unicode(arg) for arg in argv ]
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/traitlets/config/application.py", line 666, in <listcomp>
    self.argv = [cast_unicode(arg) for arg in argv ]
  File "/Users/stslve/miniconda/envs/jlab-master/lib/python3.7/site-packages/traitlets/utils/__init__.py", line 5, in cast_unicode
    return decode(s, encoding)
NameError: name 'decode' is not defined
```

```python
>>> app.launch_new_instance(['--Session.signature_scheme', "hmac-sha256", "--Session.key", "53cba141-3c99-42db-8037-0b593430d63c"])
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-83500.json
```

**Comment by blink1073** [comment]
The bug is in this [line](https://github.com/ipython/traitlets/blob/256af166d44d5ece88da642400819e3d816109ea/traitlets/utils/__init__.py#L5)

**Comment by blink1073** [comment]
Working on a fix now

**Comment by Zsailer** [comment]
This should be fixed with ipython/traitlets#611. We're working on cutting a patch release today.

**Comment by IanMatthewHuff** [comment]
Awesome. Thanks very much for the fast turnaround on this.

**Comment by blink1073** [comment]
No problem, thanks for the debug info!

**Comment by IanMatthewHuff** [comment]
I was just checking this out on my box locally. Looks like I'm still seeing the same issue after moving to traitlets 5.0.2. I was looking at the code fix that was made, and I think that there might be an issue there. The command line does run, but the signature mismatch

This code change looked like it was dealing with the UnicodeTrait. I'm not really familiar with traitlets. But I do know that the Session.key is just a CBytes. I'm not sure if it should be casting to unicode, unless that's expected.

https://github.com/ipython/ipykernel/issues/258

**Comment by blink1073** [comment]
We added a test in `Unicode`, but the fix applies to the helper function, which affects all traits that use it.

**Comment by blink1073** [comment]
Oh, I misread, let's reopen.

**Comment by blink1073** [comment]
I am headed out on vacation, so I won't be able to return to this until next Tuesday.

**Comment by minrk** [comment]
This should be fixed by https://github.com/ipython/traitlets/pull/615

**Comment by minrk** [comment]
@IanMatthewHuff traitlets 5.0.4 should be out now with the fix for this.

**Comment by IanMatthewHuff** [comment]
@minrk thanks very much. I'm out of the office right now, but I believe that someone else on my team would be able to test quick after Labor day. Thanks again.

**Comment by derekschinke** [comment]
Can confirm, the latest traitlets update has fixed this.

**Comment by blink1073** [comment]
Thanks @minrk!

**Comment by IanMatthewHuff** [comment]
Back in the office now. Thanks @minrk for the fix here.
